
version: '3'

#volumes:
#  sawtooth-drive:
#    driver: local
#    driver_opts:
#      type: none
#      device: /home/$USER/sawtooth-drive
#      o: bind

networks:
  sawtooth-network:
    #name: sawtooth_network

services:
  validator:
    image: hyperledger/sawtooth-validator:1.2
    container_name: sawtooth-validator
    volumes:
      - /home/$USER/sawtooth-drive/keys:/etc/sawtooth/keys
      - /home/$USER/sawtooth-drive/conf:/etc/sawtooth
      - /home/$USER/sawtooth-drive/data:/var/lib/sawtooth
      - /home/$USER/sawtooth-drive/log:/var/log/sawtooth
      - /home/$USER/sawtooth-drive/policy:/etc/sawtooth/policy
    expose:
      - 4004
    ports:
      - '4004:4004'
    command: |
      bash -c "
        if [ ! -f /etc/sawtooth/keys/validator.priv ]; then
          echo '........no validator key found'
          sawadm keygen
          sawtooth keygen my_key
          sawset genesis -k /root/.sawtooth/keys/my_key.priv
          echo '........key generated....'
          sawset proposal create \
                    -k /root/.sawtooth/keys/my_key.priv \
                    sawtooth.consensus.algorithm.name=Devmode \
                    sawtooth.consensus.algorithm.version=0.1 \
                    -o config.batch
          sawadm genesis config-genesis.batch config.batch
          echo '.......genesis key configured...'
        fi;
        echo '........validator key found. starting validator....'
        sawtooth-validator -vv \
          --endpoint tcp://validator:8800 \
          --bind component:tcp://eth0:4004 \
          --bind network:tcp://eth0:8800 \
          --bind consensus:tcp://eth0:5050
      "
    stop_signal: SIGKILL

  devmode-engine:
    image: hyperledger/sawtooth-devmode-engine-rust:1.2
    expose:
      - 5050
    ports:
      - '5050:5050'
    container_name: sawtooth-devmode-engine-rust-default
    depends_on:
      - validator
    entrypoint: devmode-engine-rust --connect tcp://validator:5050

  settings-tp:
    image: hyperledger/sawtooth-settings-tp:1.2
    container_name: sawtooth-settings-tp
    depends_on:
      - validator
    entrypoint: settings-tp -vv -C tcp://validator:4004

  rest-api:
    image: hyperledger/sawtooth-rest-api:1.2
    container_name: sawtooth-rest-api
    expose:
      - 8008
    ports:
      - '8008:8008'
    depends_on:
      - validator
    entrypoint: sawtooth-rest-api -vv -C tcp://validator:4004 --bind rest-api:8008

  thutech-shell:
#    build:
#      context: .
#      dockerfile: ./shell/Dockerfile
    image: hyperledger/sawtooth-shell:chime
    container_name: sawtooth-shell
    depends_on:
      - rest-api
    volumes:
      - .:/project/thutech
    command: |
      bash -c "
        tail -f /dev/null
      "

  thutech-tp:
    build:
      context: .
      dockerfile: ./processor/Dockerfile
    image: sawtooth-thutech-tp
    container_name: thutech-tp
    volumes:
      - .:/project/thutech
    depends_on:
      - thutech-shell
    command: |
      bash -c "
        sleep 1
        thutech-tp -v -C tcp://validator:4004
      "
    environment:
      # show print() message in console
      PYTHONUNBUFFERED: 1

  # Client
  thutech-rest-api:
    build:
      context: .
      dockerfile: ./rest_api/Dockerfile
    image: sawtooth-thutech-rest-api
    container_name: thutech-rest-api
    volumes:
      - .:/project/thutech
      - /home/$USER/keys:/root/.sawtooth/keys/
      #- 'key-volume: /root/.sawtooth/keys'
    ports:
      - '8000:8000'
    depends_on:
      - thutech-shell
    command: |
      bash -c "
        thutech-protogen
        thutech-rest-api \
          -B simple-supply-rest-api:8000 \
          -C validator:4004 \
          --db-host postgres \
          -vv
      "
    environment:
      # show print() message in console
      PYTHONUNBUFFERED: 1

  intkey-tp-python:
    image: hyperledger/sawtooth-intkey-tp-python:chime
    container_name: sawtooth-intkey-tp-python-default
    depends_on:
      - validator
    entrypoint: intkey-tp-python -vv -C tcp://validator:4004

  db:
    image: "postgres"
    container_name: "postgres_thutech"
    environment:
      - POSTGRES_USER=thutech_admin
      - POSTGRES_PASSWORD=y983myAqyxfM
      - POSTGRES_DB=thetech_db
    ports:
      - 54320:5432
    volumes:
      - /home/$USER/postgres-data/:/var/lib/postgresql/data

