# Generated by Django 2.2.7 on 2019-11-26 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriber', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_num', models.BigIntegerField()),
                ('block_id', models.CharField(max_length=500)),
                ('state_root_hash', models.CharField(max_length=500)),
                ('previous_block_id', models.CharField(max_length=500)),
                ('address', models.CharField(max_length=150, unique=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Block',
        ),
        migrations.DeleteModel(
            name='Record',
        ),
    ]
