# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: thutech_protobuf/product.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='thutech_protobuf/product.proto',
  package='',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n\x1ethutech_protobuf/product.proto\"\xa2\x01\n\x0bProductInfo\x12\x14\n\x0cproduct_name\x18\x01 \x02(\t\x12\x13\n\x0bproduct_sku\x18\x02 \x01(\t\x12\x18\n\x10ship_to_location\x18\x03 \x01(\t\x12#\n\x06\x61\x63tion\x18\x04 \x01(\x0e\x32\x13.ProductInfo.Action\")\n\x06\x41\x63tion\x12\x0f\n\x0b\x43REATE_INFO\x10\x01\x12\x0e\n\nCHECK_INFO\x10\x02')
)



_PRODUCTINFO_ACTION = _descriptor.EnumDescriptor(
  name='Action',
  full_name='ProductInfo.Action',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='CREATE_INFO', index=0, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CHECK_INFO', index=1, number=2,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=156,
  serialized_end=197,
)
_sym_db.RegisterEnumDescriptor(_PRODUCTINFO_ACTION)


_PRODUCTINFO = _descriptor.Descriptor(
  name='ProductInfo',
  full_name='ProductInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='product_name', full_name='ProductInfo.product_name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='product_sku', full_name='ProductInfo.product_sku', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ship_to_location', full_name='ProductInfo.ship_to_location', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='action', full_name='ProductInfo.action', index=3,
      number=4, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _PRODUCTINFO_ACTION,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=35,
  serialized_end=197,
)

_PRODUCTINFO.fields_by_name['action'].enum_type = _PRODUCTINFO_ACTION
_PRODUCTINFO_ACTION.containing_type = _PRODUCTINFO
DESCRIPTOR.message_types_by_name['ProductInfo'] = _PRODUCTINFO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ProductInfo = _reflection.GeneratedProtocolMessageType('ProductInfo', (_message.Message,), {
  'DESCRIPTOR' : _PRODUCTINFO,
  '__module__' : 'thutech_protobuf.product_pb2'
  # @@protoc_insertion_point(class_scope:ProductInfo)
  })
_sym_db.RegisterMessage(ProductInfo)


# @@protoc_insertion_point(module_scope)
