# Generated by Django 2.2.7 on 2019-11-21 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductQue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True, unique=True)),
                ('is_resolved', models.BooleanField(default=False)),
                ('status', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
    ]
