# Generated by Django 2.2.7 on 2019-12-04 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productque',
            name='date',
            field=models.DateField(unique=True),
        ),
    ]
