# Generated by Django 2.2.7 on 2019-12-04 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20191204_0334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productque',
            name='status',
            field=models.TextField(blank=True, null=True),
        ),
    ]
